countryNames = {
    'PS': 'Palestine',
    'SA': 'Saudi Arabia',
    'IR': 'Iran',
    'AE': 'United Arab Emirates',
    'QA': 'Qatar',
    'EG': 'Egypt',
    'IL': 'Israel',
    'IQ': 'Iraq',
    'JO': 'Jordan',
    'KW': 'Kuwait',
    'LB': 'Lebanon',
    'OM': 'Oman',
    'SY': 'Syria',
    'YE': 'Yemen',
    'IN': 'India',
    'CN': 'China',
    'SG': 'Singapore',
    'JP': 'Japan',
    'VN': 'Viet Nam',
    'KR': 'Korea',
    'BD': 'Bangladesh',
    'HK': 'Hong Kong',
    'MY': 'Malaysia',
    'TH': 'Thailand',
    'PH': 'Philippines',
    'TW': 'Taiwan',
    'KH': 'Cambodia',
    'ID': 'Indonesia',
    'PK': 'Pakistan',
    'NP': 'Nepal',
    'LK': 'Sri Lanka',
    'MM': 'Myanmar',
    'RU': 'Russian Federation',
    'DE': 'Germany',
    'GB': 'United Kingdom',
    'FR': 'France',
    'IT': 'Italy',
    'ES': 'Spain',
    'NL': 'Netherlands',
    'UA': 'Ukraine',
    'PL': 'Poland',
    'SE': 'Sweden',
    'NO': 'Norway',
    'FI': 'Finland',
    'DK': 'Denmark',
    'RO': 'Romania',
    'CZ': 'Czechia',
    'BE': 'Belgium',
    'AT': 'Austria',
    'HU': 'Hungary',
    'BG': 'Bulgaria',
    'GR': 'Greece',
    'PT': 'Portugal',
    'CH': 'Switzerland',
    'SK': 'Slovakia',
    'LV': 'Latvia',
    'LT': 'Lithuania',
    'EE': 'Estonia',
    'IE': 'Ireland',
    'IS': 'Iceland',
    'US': 'United States of America',
    'CA': 'Canada',
    'BR': 'Brazil',
    'MX': 'Mexico',
    'AR': 'Argentina',
    'CL': 'Chile',
    'CO': 'Colombia',
    'PE': 'Peru',
    'VE': 'Venezuela',
    'EC': 'Ecuador',
    'UY': 'Uruguay',
    'BO': 'Bolivia',
    'PY': 'Paraguay',
    'GY': 'Guyana',
    'ZA': 'South Africa',
    'NG': 'Nigeria',
    'DZ': 'Algeria',
    'MA': 'Morocco',
    'KE': 'Kenya',
    'GH': 'Ghana',
    'UG': 'Uganda',
    'TZ': 'Tanzania',
    'SN': 'Senegal',
    'ET': 'Ethiopia',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
    'CM': 'Cameroon',
    'CI': "Côte d'Ivoire",
    'MW': 'Malawi',
    'MU': 'Mauritius',
    'RW': 'Rwanda',
    'BF': 'Burkina Faso',
    'ML': 'Mali',
    'NE': 'Niger',
    'BI': 'Burundi',
    'AU': 'Australia',
    'NZ': 'New Zealand',
    'FJ': 'Fiji',
    'PG': 'Papua New Guinea',
  };
